/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetLoadApp200,
  GetLoadApp403,
  GetLoadApp500
} from '../generated.schemas';

import { customInstance } from '../../client';




export const getLoadApp = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetLoadApp200>(
      {url: `/load-app`, method: 'GET', signal
    },
      );
    }
  



export const getGetLoadAppQueryKey = () => {
    return [
    `/load-app`
    ] as const;
    }

    
export const getGetLoadAppQueryOptions = <TData = Awaited<ReturnType<typeof getLoadApp>>, TError = GetLoadApp403 | GetLoadApp500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoadApp>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLoadAppQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLoadApp>>> = ({ signal }) => getLoadApp(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLoadApp>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLoadAppQueryResult = NonNullable<Awaited<ReturnType<typeof getLoadApp>>>
export type GetLoadAppQueryError = GetLoadApp403 | GetLoadApp500


export function useGetLoadApp<TData = Awaited<ReturnType<typeof getLoadApp>>, TError = GetLoadApp403 | GetLoadApp500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoadApp>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLoadApp>>,
          TError,
          Awaited<ReturnType<typeof getLoadApp>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLoadApp<TData = Awaited<ReturnType<typeof getLoadApp>>, TError = GetLoadApp403 | GetLoadApp500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoadApp>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLoadApp>>,
          TError,
          Awaited<ReturnType<typeof getLoadApp>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLoadApp<TData = Awaited<ReturnType<typeof getLoadApp>>, TError = GetLoadApp403 | GetLoadApp500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoadApp>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLoadApp<TData = Awaited<ReturnType<typeof getLoadApp>>, TError = GetLoadApp403 | GetLoadApp500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoadApp>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLoadAppQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




