/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getUserPreferencesQueryParams = zod.object({
  "userId": zod.string()
})

export const getUserPreferencesResponse = zod.unknown().nullable()

export const putUserPreferencesBody = zod.object({
  "newPreferences": zod.object({
  "userId": zod.string().optional(),
  "pillRegime": zod.enum(['none', '21on7off', '21on7placebo', '21continous', '28continous']).optional(),
  "startDate": zod.string().optional(),
  "updatedAt": zod.iso.date().optional()
})
})

export const putUserPreferencesResponse = zod.object({
  "message": zod.string()
})

