/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetPillEvents200,
  GetPillEvents403,
  GetPillEvents500,
  GetPillEventsParams,
  PostPillEvents200,
  PostPillEvents500,
  PostPillEventsBody
} from '../generated.schemas';

import { customInstance } from '../../client';




export const getPillEvents = (
    params: GetPillEventsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetPillEvents200>(
      {url: `/pill-events`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetPillEventsQueryKey = (params?: GetPillEventsParams,) => {
    return [
    `/pill-events`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetPillEventsQueryOptions = <TData = Awaited<ReturnType<typeof getPillEvents>>, TError = GetPillEvents403 | GetPillEvents500>(params: GetPillEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPillEvents>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPillEventsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPillEvents>>> = ({ signal }) => getPillEvents(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPillEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPillEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getPillEvents>>>
export type GetPillEventsQueryError = GetPillEvents403 | GetPillEvents500


export function useGetPillEvents<TData = Awaited<ReturnType<typeof getPillEvents>>, TError = GetPillEvents403 | GetPillEvents500>(
 params: GetPillEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPillEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPillEvents>>,
          TError,
          Awaited<ReturnType<typeof getPillEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPillEvents<TData = Awaited<ReturnType<typeof getPillEvents>>, TError = GetPillEvents403 | GetPillEvents500>(
 params: GetPillEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPillEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPillEvents>>,
          TError,
          Awaited<ReturnType<typeof getPillEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPillEvents<TData = Awaited<ReturnType<typeof getPillEvents>>, TError = GetPillEvents403 | GetPillEvents500>(
 params: GetPillEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPillEvents>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetPillEvents<TData = Awaited<ReturnType<typeof getPillEvents>>, TError = GetPillEvents403 | GetPillEvents500>(
 params: GetPillEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPillEvents>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPillEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postPillEvents = (
    postPillEventsBody: PostPillEventsBody,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PostPillEvents200>(
      {url: `/pill-events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postPillEventsBody, signal
    },
      );
    }
  


export const getPostPillEventsMutationOptions = <TError = PostPillEvents500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPillEvents>>, TError,{data: PostPillEventsBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postPillEvents>>, TError,{data: PostPillEventsBody}, TContext> => {

const mutationKey = ['postPillEvents'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postPillEvents>>, {data: PostPillEventsBody}> = (props) => {
          const {data} = props ?? {};

          return  postPillEvents(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostPillEventsMutationResult = NonNullable<Awaited<ReturnType<typeof postPillEvents>>>
    export type PostPillEventsMutationBody = PostPillEventsBody
    export type PostPillEventsMutationError = PostPillEvents500

    export const usePostPillEvents = <TError = PostPillEvents500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postPillEvents>>, TError,{data: PostPillEventsBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postPillEvents>>,
        TError,
        {data: PostPillEventsBody},
        TContext
      > => {

      const mutationOptions = getPostPillEventsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    