/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetUserPreferences200,
  GetUserPreferences403,
  GetUserPreferences500,
  GetUserPreferencesParams,
  PutUserPreferences200,
  PutUserPreferences500,
  PutUserPreferencesBody
} from '../generated.schemas';

import { customInstance } from '../../client';




export const getUserPreferences = (
    params: GetUserPreferencesParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserPreferences200>(
      {url: `/user-preferences`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetUserPreferencesQueryKey = (params?: GetUserPreferencesParams,) => {
    return [
    `/user-preferences`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetUserPreferencesQueryOptions = <TData = Awaited<ReturnType<typeof getUserPreferences>>, TError = GetUserPreferences403 | GetUserPreferences500>(params: GetUserPreferencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPreferences>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserPreferencesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserPreferences>>> = ({ signal }) => getUserPreferences(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserPreferences>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserPreferencesQueryResult = NonNullable<Awaited<ReturnType<typeof getUserPreferences>>>
export type GetUserPreferencesQueryError = GetUserPreferences403 | GetUserPreferences500


export function useGetUserPreferences<TData = Awaited<ReturnType<typeof getUserPreferences>>, TError = GetUserPreferences403 | GetUserPreferences500>(
 params: GetUserPreferencesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPreferences>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPreferences>>,
          TError,
          Awaited<ReturnType<typeof getUserPreferences>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserPreferences<TData = Awaited<ReturnType<typeof getUserPreferences>>, TError = GetUserPreferences403 | GetUserPreferences500>(
 params: GetUserPreferencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPreferences>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserPreferences>>,
          TError,
          Awaited<ReturnType<typeof getUserPreferences>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserPreferences<TData = Awaited<ReturnType<typeof getUserPreferences>>, TError = GetUserPreferences403 | GetUserPreferences500>(
 params: GetUserPreferencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPreferences>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserPreferences<TData = Awaited<ReturnType<typeof getUserPreferences>>, TError = GetUserPreferences403 | GetUserPreferences500>(
 params: GetUserPreferencesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserPreferences>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserPreferencesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putUserPreferences = (
    putUserPreferencesBody: PutUserPreferencesBody,
 ) => {
      
      
      return customInstance<PutUserPreferences200>(
      {url: `/user-preferences`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putUserPreferencesBody
    },
      );
    }
  


export const getPutUserPreferencesMutationOptions = <TError = PutUserPreferences500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserPreferences>>, TError,{data: PutUserPreferencesBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putUserPreferences>>, TError,{data: PutUserPreferencesBody}, TContext> => {

const mutationKey = ['putUserPreferences'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUserPreferences>>, {data: PutUserPreferencesBody}> = (props) => {
          const {data} = props ?? {};

          return  putUserPreferences(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutUserPreferencesMutationResult = NonNullable<Awaited<ReturnType<typeof putUserPreferences>>>
    export type PutUserPreferencesMutationBody = PutUserPreferencesBody
    export type PutUserPreferencesMutationError = PutUserPreferences500

    export const usePutUserPreferences = <TError = PutUserPreferences500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserPreferences>>, TError,{data: PutUserPreferencesBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putUserPreferences>>,
        TError,
        {data: PutUserPreferencesBody},
        TContext
      > => {

      const mutationOptions = getPutUserPreferencesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    