/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetAccessIncomingInvites200,
  GetAccessIncomingInvites500,
  GetAccessOutgoingGrants200Item,
  GetAccessOutgoingGrants500,
  PostAccessInvite200,
  PostAccessInvite400,
  PostAccessInvite500,
  PostAccessInviteParams,
  PutAccessApproveInvite200,
  PutAccessApproveInvite404,
  PutAccessApproveInvite500,
  PutAccessApproveInviteParams,
  PutAccessIgnoreInvite200,
  PutAccessIgnoreInvite500,
  PutAccessIgnoreInviteParams,
  PutAccessRevokeGrant200,
  PutAccessRevokeGrant500,
  PutAccessRevokeGrantParams
} from '../generated.schemas';

import { customInstance } from '../../client';




export const getAccessOutgoingGrants = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetAccessOutgoingGrants200Item[]>(
      {url: `/access/outgoing-grants`, method: 'GET', signal
    },
      );
    }
  



export const getGetAccessOutgoingGrantsQueryKey = () => {
    return [
    `/access/outgoing-grants`
    ] as const;
    }

    
export const getGetAccessOutgoingGrantsQueryOptions = <TData = Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError = GetAccessOutgoingGrants500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAccessOutgoingGrantsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccessOutgoingGrants>>> = ({ signal }) => getAccessOutgoingGrants(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAccessOutgoingGrantsQueryResult = NonNullable<Awaited<ReturnType<typeof getAccessOutgoingGrants>>>
export type GetAccessOutgoingGrantsQueryError = GetAccessOutgoingGrants500


export function useGetAccessOutgoingGrants<TData = Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError = GetAccessOutgoingGrants500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccessOutgoingGrants>>,
          TError,
          Awaited<ReturnType<typeof getAccessOutgoingGrants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAccessOutgoingGrants<TData = Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError = GetAccessOutgoingGrants500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccessOutgoingGrants>>,
          TError,
          Awaited<ReturnType<typeof getAccessOutgoingGrants>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAccessOutgoingGrants<TData = Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError = GetAccessOutgoingGrants500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAccessOutgoingGrants<TData = Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError = GetAccessOutgoingGrants500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessOutgoingGrants>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAccessOutgoingGrantsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getAccessIncomingInvites = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetAccessIncomingInvites200>(
      {url: `/access/incoming-invites`, method: 'GET', signal
    },
      );
    }
  



export const getGetAccessIncomingInvitesQueryKey = () => {
    return [
    `/access/incoming-invites`
    ] as const;
    }

    
export const getGetAccessIncomingInvitesQueryOptions = <TData = Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError = GetAccessIncomingInvites500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAccessIncomingInvitesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccessIncomingInvites>>> = ({ signal }) => getAccessIncomingInvites(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAccessIncomingInvitesQueryResult = NonNullable<Awaited<ReturnType<typeof getAccessIncomingInvites>>>
export type GetAccessIncomingInvitesQueryError = GetAccessIncomingInvites500


export function useGetAccessIncomingInvites<TData = Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError = GetAccessIncomingInvites500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccessIncomingInvites>>,
          TError,
          Awaited<ReturnType<typeof getAccessIncomingInvites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAccessIncomingInvites<TData = Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError = GetAccessIncomingInvites500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccessIncomingInvites>>,
          TError,
          Awaited<ReturnType<typeof getAccessIncomingInvites>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAccessIncomingInvites<TData = Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError = GetAccessIncomingInvites500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAccessIncomingInvites<TData = Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError = GetAccessIncomingInvites500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccessIncomingInvites>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAccessIncomingInvitesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const postAccessInvite = (
    params: PostAccessInviteParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PostAccessInvite200>(
      {url: `/access/invite`, method: 'POST',
        params, signal
    },
      );
    }
  


export const getPostAccessInviteMutationOptions = <TError = PostAccessInvite400 | PostAccessInvite500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAccessInvite>>, TError,{params: PostAccessInviteParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAccessInvite>>, TError,{params: PostAccessInviteParams}, TContext> => {

const mutationKey = ['postAccessInvite'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAccessInvite>>, {params: PostAccessInviteParams}> = (props) => {
          const {params} = props ?? {};

          return  postAccessInvite(params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAccessInviteMutationResult = NonNullable<Awaited<ReturnType<typeof postAccessInvite>>>
    
    export type PostAccessInviteMutationError = PostAccessInvite400 | PostAccessInvite500

    export const usePostAccessInvite = <TError = PostAccessInvite400 | PostAccessInvite500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAccessInvite>>, TError,{params: PostAccessInviteParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAccessInvite>>,
        TError,
        {params: PostAccessInviteParams},
        TContext
      > => {

      const mutationOptions = getPostAccessInviteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const putAccessApproveInvite = (
    params: PutAccessApproveInviteParams,
 ) => {
      
      
      return customInstance<PutAccessApproveInvite200>(
      {url: `/access/approve-invite`, method: 'PUT',
        params
    },
      );
    }
  


export const getPutAccessApproveInviteMutationOptions = <TError = PutAccessApproveInvite404 | PutAccessApproveInvite500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAccessApproveInvite>>, TError,{params: PutAccessApproveInviteParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putAccessApproveInvite>>, TError,{params: PutAccessApproveInviteParams}, TContext> => {

const mutationKey = ['putAccessApproveInvite'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAccessApproveInvite>>, {params: PutAccessApproveInviteParams}> = (props) => {
          const {params} = props ?? {};

          return  putAccessApproveInvite(params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutAccessApproveInviteMutationResult = NonNullable<Awaited<ReturnType<typeof putAccessApproveInvite>>>
    
    export type PutAccessApproveInviteMutationError = PutAccessApproveInvite404 | PutAccessApproveInvite500

    export const usePutAccessApproveInvite = <TError = PutAccessApproveInvite404 | PutAccessApproveInvite500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAccessApproveInvite>>, TError,{params: PutAccessApproveInviteParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAccessApproveInvite>>,
        TError,
        {params: PutAccessApproveInviteParams},
        TContext
      > => {

      const mutationOptions = getPutAccessApproveInviteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const putAccessIgnoreInvite = (
    params: PutAccessIgnoreInviteParams,
 ) => {
      
      
      return customInstance<PutAccessIgnoreInvite200>(
      {url: `/access/ignore-invite`, method: 'PUT',
        params
    },
      );
    }
  


export const getPutAccessIgnoreInviteMutationOptions = <TError = PutAccessIgnoreInvite500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAccessIgnoreInvite>>, TError,{params: PutAccessIgnoreInviteParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putAccessIgnoreInvite>>, TError,{params: PutAccessIgnoreInviteParams}, TContext> => {

const mutationKey = ['putAccessIgnoreInvite'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAccessIgnoreInvite>>, {params: PutAccessIgnoreInviteParams}> = (props) => {
          const {params} = props ?? {};

          return  putAccessIgnoreInvite(params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutAccessIgnoreInviteMutationResult = NonNullable<Awaited<ReturnType<typeof putAccessIgnoreInvite>>>
    
    export type PutAccessIgnoreInviteMutationError = PutAccessIgnoreInvite500

    export const usePutAccessIgnoreInvite = <TError = PutAccessIgnoreInvite500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAccessIgnoreInvite>>, TError,{params: PutAccessIgnoreInviteParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAccessIgnoreInvite>>,
        TError,
        {params: PutAccessIgnoreInviteParams},
        TContext
      > => {

      const mutationOptions = getPutAccessIgnoreInviteMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    export const putAccessRevokeGrant = (
    params: PutAccessRevokeGrantParams,
 ) => {
      
      
      return customInstance<PutAccessRevokeGrant200>(
      {url: `/access/revoke-grant`, method: 'PUT',
        params
    },
      );
    }
  


export const getPutAccessRevokeGrantMutationOptions = <TError = PutAccessRevokeGrant500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAccessRevokeGrant>>, TError,{params: PutAccessRevokeGrantParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putAccessRevokeGrant>>, TError,{params: PutAccessRevokeGrantParams}, TContext> => {

const mutationKey = ['putAccessRevokeGrant'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAccessRevokeGrant>>, {params: PutAccessRevokeGrantParams}> = (props) => {
          const {params} = props ?? {};

          return  putAccessRevokeGrant(params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutAccessRevokeGrantMutationResult = NonNullable<Awaited<ReturnType<typeof putAccessRevokeGrant>>>
    
    export type PutAccessRevokeGrantMutationError = PutAccessRevokeGrant500

    export const usePutAccessRevokeGrant = <TError = PutAccessRevokeGrant500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAccessRevokeGrant>>, TError,{params: PutAccessRevokeGrantParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAccessRevokeGrant>>,
        TError,
        {params: PutAccessRevokeGrantParams},
        TContext
      > => {

      const mutationOptions = getPutAccessRevokeGrantMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    