/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getUserProfilesResponseUsernameMin = 3;
export const getUserProfilesResponseUsernameMax = 32;


export const getUserProfilesResponseUsernameRegExp = new RegExp('^[a-zA-Z0-9][a-zA-Z0-9_-]*$');


export const getUserProfilesResponse = zod.object({
  "userId": zod.string(),
  "username": zod.string().min(getUserProfilesResponseUsernameMin).max(getUserProfilesResponseUsernameMax).regex(getUserProfilesResponseUsernameRegExp).nullable(),
  "viewing": zod.string(),
  "updatedAt": zod.iso.date()
})

export const putUserProfilesBodyNewProfileUsernameMin = 3;
export const putUserProfilesBodyNewProfileUsernameMax = 32;


export const putUserProfilesBodyNewProfileUsernameRegExp = new RegExp('^[a-zA-Z0-9][a-zA-Z0-9_-]*$');


export const putUserProfilesBody = zod.object({
  "newProfile": zod.object({
  "userId": zod.string().optional(),
  "username": zod.string().min(putUserProfilesBodyNewProfileUsernameMin).max(putUserProfilesBodyNewProfileUsernameMax).regex(putUserProfilesBodyNewProfileUsernameRegExp).nullish(),
  "viewing": zod.string().optional(),
  "updatedAt": zod.iso.date().optional()
})
})

export const putUserProfilesResponse = zod.object({
  "message": zod.string()
})

