/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
/**
 * @nullable
 */
export type GetSession200Session = unknown | null;

/**
 * @nullable
 */
export type GetSession200User = unknown | null;

export type GetSession200 = {
  /** @nullable */
  session?: GetSession200Session;
  /** @nullable */
  user?: GetSession200User;
};

export type GetAccessOutgoingGrants200Item = {
  id: string;
  ownerId: string;
  granteeId: string;
  createdAt: string;
  /** @nullable */
  updatedAt: string | null;
  active: boolean;
  /**
   * @minLength 3
   * @maxLength 32
   * @nullable
   * @pattern ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
   */
  granteeUsername: string | null;
};

export type GetAccessOutgoingGrants500 = {
  success: boolean;
  message: string;
};

export type GetAccessIncomingInvites200PendingItemStatus = typeof GetAccessIncomingInvites200PendingItemStatus[keyof typeof GetAccessIncomingInvites200PendingItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAccessIncomingInvites200PendingItemStatus = {
  pending: 'pending',
  approved: 'approved',
  revoked: 'revoked',
  ignored: 'ignored',
} as const;

export type GetAccessIncomingInvites200PendingItem = {
  id: string;
  ownerId: string;
  inviteeId: string;
  status: GetAccessIncomingInvites200PendingItemStatus;
  createdAt: string;
  updatedAt: string;
  /**
   * @minLength 3
   * @maxLength 32
   * @nullable
   * @pattern ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
   */
  ownerUsername: string | null;
};

export type GetAccessIncomingInvites200ApprovedItemStatus = typeof GetAccessIncomingInvites200ApprovedItemStatus[keyof typeof GetAccessIncomingInvites200ApprovedItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetAccessIncomingInvites200ApprovedItemStatus = {
  pending: 'pending',
  approved: 'approved',
  revoked: 'revoked',
  ignored: 'ignored',
} as const;

export type GetAccessIncomingInvites200ApprovedItem = {
  id: string;
  ownerId: string;
  inviteeId: string;
  status: GetAccessIncomingInvites200ApprovedItemStatus;
  createdAt: string;
  updatedAt: string;
  /**
   * @minLength 3
   * @maxLength 32
   * @nullable
   * @pattern ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
   */
  ownerUsername: string | null;
};

export type GetAccessIncomingInvites200 = {
  pending: GetAccessIncomingInvites200PendingItem[];
  approved: GetAccessIncomingInvites200ApprovedItem[];
};

export type GetAccessIncomingInvites500 = {
  success: boolean;
  message: string;
};

export type PostAccessInviteParams = {
/**
 * @minLength 3
 * @maxLength 32
 * @pattern ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
 */
username: string;
};

export type PostAccessInvite200 = {
  success: boolean;
  message: string;
};

export type PostAccessInvite400 = {
  success: boolean;
  message: string;
};

export type PostAccessInvite500 = {
  success: boolean;
  message: string;
};

export type PutAccessApproveInviteParams = {
userId: string;
};

export type PutAccessApproveInvite200 = {
  success: boolean;
  message: string;
};

export type PutAccessApproveInvite404 = {
  success: boolean;
  message: string;
};

export type PutAccessApproveInvite500 = {
  success: boolean;
  message: string;
};

export type PutAccessIgnoreInviteParams = {
userId: string;
};

export type PutAccessIgnoreInvite200 = {
  success: boolean;
  message: string;
};

export type PutAccessIgnoreInvite500 = {
  success: boolean;
  message: string;
};

export type PutAccessRevokeGrantParams = {
userId: string;
};

export type PutAccessRevokeGrant200 = {
  success: boolean;
  message: string;
};

export type PutAccessRevokeGrant500 = {
  success: boolean;
  message: string;
};

export type GetPillEventsParams = {
ownerId: string;
startDate: string;
};

export type GetPillEvents200 = {[key: string]: boolean};

export type GetPillEvents403 = {
  success: boolean;
  message: string;
};

export type GetPillEvents500 = {
  error: string;
};

export type PostPillEventsBodyPillEvent = {
  pillDate: string;
  pillTaken: boolean;
};

export type PostPillEventsBody = {
  pillEvent: PostPillEventsBodyPillEvent;
};

export type PostPillEvents200 = {
  message: string;
};

export type PostPillEvents500 = {
  error: string;
};

export type GetUserPreferencesParams = {
userId: string;
};

/**
 * @nullable
 */
export type GetUserPreferences200 = unknown | null;

export type GetUserPreferences403 = {
  success: boolean;
  message: string;
};

export type GetUserPreferences500 = {
  error: string;
};

export type PutUserPreferencesBodyNewPreferencesPillRegime = typeof PutUserPreferencesBodyNewPreferencesPillRegime[keyof typeof PutUserPreferencesBodyNewPreferencesPillRegime];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PutUserPreferencesBodyNewPreferencesPillRegime = {
  none: 'none',
  '21on7off': '21on7off',
  '21on7placebo': '21on7placebo',
  '21continous': '21continous',
  '28continous': '28continous',
} as const;

export type PutUserPreferencesBodyNewPreferences = {
  userId?: string;
  pillRegime?: PutUserPreferencesBodyNewPreferencesPillRegime;
  startDate?: string;
  updatedAt?: string;
};

export type PutUserPreferencesBody = {
  newPreferences: PutUserPreferencesBodyNewPreferences;
};

export type PutUserPreferences200 = {
  message: string;
};

export type PutUserPreferences500 = {
  error: string;
};

export type GetUserProfiles200 = {
  userId: string;
  /**
   * @minLength 3
   * @maxLength 32
   * @nullable
   * @pattern ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
   */
  username: string | null;
  viewing: string;
  updatedAt: string;
};

export type GetUserProfiles500 = {
  error: string;
};

export type PutUserProfilesBodyNewProfile = {
  userId?: string;
  /**
   * @minLength 3
   * @maxLength 32
   * @nullable
   * @pattern ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
   */
  username?: string | null;
  viewing?: string;
  updatedAt?: string;
};

export type PutUserProfilesBody = {
  newProfile: PutUserProfilesBodyNewProfile;
};

export type PutUserProfiles200 = {
  message: string;
};

export type PutUserProfiles500 = {
  error: string;
};

export type GetLoadApp200Profile = {
  userId: string;
  /**
   * @minLength 3
   * @maxLength 32
   * @nullable
   * @pattern ^[a-zA-Z0-9][a-zA-Z0-9_-]*$
   */
  username: string | null;
  viewing: string;
  updatedAt: string;
};

export type GetLoadApp200ViewedPreferencesPillRegime = typeof GetLoadApp200ViewedPreferencesPillRegime[keyof typeof GetLoadApp200ViewedPreferencesPillRegime];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetLoadApp200ViewedPreferencesPillRegime = {
  none: 'none',
  '21on7off': '21on7off',
  '21on7placebo': '21on7placebo',
  '21continous': '21continous',
  '28continous': '28continous',
} as const;

export type GetLoadApp200ViewedPreferences = {
  userId: string;
  pillRegime: GetLoadApp200ViewedPreferencesPillRegime;
  startDate: string;
  updatedAt: string;
};

export type GetLoadApp200ViewedPillStates = {[key: string]: boolean};

export type GetLoadApp200 = {
  profile: GetLoadApp200Profile;
  viewedPreferences: GetLoadApp200ViewedPreferences;
  viewedPillStates: GetLoadApp200ViewedPillStates;
};

export type GetLoadApp403 = {
  error: string;
};

export type GetLoadApp500 = {
  error: string;
};

