/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetUserProfiles200,
  GetUserProfiles500,
  PutUserProfiles200,
  PutUserProfiles500,
  PutUserProfilesBody
} from '../generated.schemas';

import { customInstance } from '../../client';




export const getUserProfiles = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<GetUserProfiles200>(
      {url: `/user-profiles`, method: 'GET', signal
    },
      );
    }
  



export const getGetUserProfilesQueryKey = () => {
    return [
    `/user-profiles`
    ] as const;
    }

    
export const getGetUserProfilesQueryOptions = <TData = Awaited<ReturnType<typeof getUserProfiles>>, TError = GetUserProfiles500>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfiles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserProfilesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserProfiles>>> = ({ signal }) => getUserProfiles(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserProfiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserProfilesQueryResult = NonNullable<Awaited<ReturnType<typeof getUserProfiles>>>
export type GetUserProfilesQueryError = GetUserProfiles500


export function useGetUserProfiles<TData = Awaited<ReturnType<typeof getUserProfiles>>, TError = GetUserProfiles500>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfiles>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfiles>>,
          TError,
          Awaited<ReturnType<typeof getUserProfiles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfiles<TData = Awaited<ReturnType<typeof getUserProfiles>>, TError = GetUserProfiles500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfiles>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserProfiles>>,
          TError,
          Awaited<ReturnType<typeof getUserProfiles>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserProfiles<TData = Awaited<ReturnType<typeof getUserProfiles>>, TError = GetUserProfiles500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfiles>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUserProfiles<TData = Awaited<ReturnType<typeof getUserProfiles>>, TError = GetUserProfiles500>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserProfiles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserProfilesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const putUserProfiles = (
    putUserProfilesBody: PutUserProfilesBody,
 ) => {
      
      
      return customInstance<PutUserProfiles200>(
      {url: `/user-profiles`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putUserProfilesBody
    },
      );
    }
  


export const getPutUserProfilesMutationOptions = <TError = PutUserProfiles500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserProfiles>>, TError,{data: PutUserProfilesBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putUserProfiles>>, TError,{data: PutUserProfilesBody}, TContext> => {

const mutationKey = ['putUserProfiles'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putUserProfiles>>, {data: PutUserProfilesBody}> = (props) => {
          const {data} = props ?? {};

          return  putUserProfiles(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutUserProfilesMutationResult = NonNullable<Awaited<ReturnType<typeof putUserProfiles>>>
    export type PutUserProfilesMutationBody = PutUserProfilesBody
    export type PutUserProfilesMutationError = PutUserProfiles500

    export const usePutUserProfiles = <TError = PutUserProfiles500,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putUserProfiles>>, TError,{data: PutUserProfilesBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putUserProfiles>>,
        TError,
        {data: PutUserProfilesBody},
        TContext
      > => {

      const mutationOptions = getPutUserProfilesMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    