/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getLoadAppResponseProfileUsernameMin = 3;
export const getLoadAppResponseProfileUsernameMax = 32;


export const getLoadAppResponseProfileUsernameRegExp = new RegExp('^[a-zA-Z0-9][a-zA-Z0-9_-]*$');


export const getLoadAppResponse = zod.object({
  "profile": zod.object({
  "userId": zod.string(),
  "username": zod.string().min(getLoadAppResponseProfileUsernameMin).max(getLoadAppResponseProfileUsernameMax).regex(getLoadAppResponseProfileUsernameRegExp).nullable(),
  "viewing": zod.string(),
  "updatedAt": zod.iso.date()
}),
  "viewedPreferences": zod.object({
  "userId": zod.string(),
  "pillRegime": zod.enum(['none', '21on7off', '21on7placebo', '21continous', '28continous']),
  "startDate": zod.string(),
  "updatedAt": zod.iso.date()
}),
  "viewedPillStates": zod.record(zod.string(), zod.boolean())
})

