/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getPillEventsQueryParams = zod.object({
  "ownerId": zod.string(),
  "startDate": zod.string()
})

export const getPillEventsResponse = zod.record(zod.string(), zod.boolean())

export const postPillEventsBody = zod.object({
  "pillEvent": zod.object({
  "pillDate": zod.string(),
  "pillTaken": zod.boolean()
})
})

