/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getAccessOutgoingGrantsResponseGranteeUsernameMin = 3;
export const getAccessOutgoingGrantsResponseGranteeUsernameMax = 32;


export const getAccessOutgoingGrantsResponseGranteeUsernameRegExp = new RegExp('^[a-zA-Z0-9][a-zA-Z0-9_-]*$');


export const getAccessOutgoingGrantsResponseItem = zod.object({
  "id": zod.string(),
  "ownerId": zod.string(),
  "granteeId": zod.string(),
  "createdAt": zod.iso.date(),
  "updatedAt": zod.iso.date().nullable(),
  "active": zod.boolean(),
  "granteeUsername": zod.string().min(getAccessOutgoingGrantsResponseGranteeUsernameMin).max(getAccessOutgoingGrantsResponseGranteeUsernameMax).regex(getAccessOutgoingGrantsResponseGranteeUsernameRegExp).nullable()
})
export const getAccessOutgoingGrantsResponse = zod.array(getAccessOutgoingGrantsResponseItem)

export const getAccessIncomingInvitesResponsePendingItemOwnerUsernameMin = 3;
export const getAccessIncomingInvitesResponsePendingItemOwnerUsernameMax = 32;


export const getAccessIncomingInvitesResponsePendingItemOwnerUsernameRegExp = new RegExp('^[a-zA-Z0-9][a-zA-Z0-9_-]*$');
export const getAccessIncomingInvitesResponseApprovedItemOwnerUsernameMin = 3;
export const getAccessIncomingInvitesResponseApprovedItemOwnerUsernameMax = 32;


export const getAccessIncomingInvitesResponseApprovedItemOwnerUsernameRegExp = new RegExp('^[a-zA-Z0-9][a-zA-Z0-9_-]*$');


export const getAccessIncomingInvitesResponse = zod.object({
  "pending": zod.array(zod.object({
  "id": zod.string(),
  "ownerId": zod.string(),
  "inviteeId": zod.string(),
  "status": zod.enum(['pending', 'approved', 'revoked', 'ignored']),
  "createdAt": zod.iso.date(),
  "updatedAt": zod.iso.date(),
  "ownerUsername": zod.string().min(getAccessIncomingInvitesResponsePendingItemOwnerUsernameMin).max(getAccessIncomingInvitesResponsePendingItemOwnerUsernameMax).regex(getAccessIncomingInvitesResponsePendingItemOwnerUsernameRegExp).nullable()
})),
  "approved": zod.array(zod.object({
  "id": zod.string(),
  "ownerId": zod.string(),
  "inviteeId": zod.string(),
  "status": zod.enum(['pending', 'approved', 'revoked', 'ignored']),
  "createdAt": zod.iso.date(),
  "updatedAt": zod.iso.date(),
  "ownerUsername": zod.string().min(getAccessIncomingInvitesResponseApprovedItemOwnerUsernameMin).max(getAccessIncomingInvitesResponseApprovedItemOwnerUsernameMax).regex(getAccessIncomingInvitesResponseApprovedItemOwnerUsernameRegExp).nullable()
}))
})

export const postAccessInviteQueryUsernameMin = 3;
export const postAccessInviteQueryUsernameMax = 32;


export const postAccessInviteQueryUsernameRegExp = new RegExp('^[a-zA-Z0-9][a-zA-Z0-9_-]*$');


export const postAccessInviteQueryParams = zod.object({
  "username": zod.string().min(postAccessInviteQueryUsernameMin).max(postAccessInviteQueryUsernameMax).regex(postAccessInviteQueryUsernameRegExp)
})

export const postAccessInviteResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})

export const putAccessApproveInviteQueryParams = zod.object({
  "userId": zod.string()
})

export const putAccessApproveInviteResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})

export const putAccessIgnoreInviteQueryParams = zod.object({
  "userId": zod.string()
})

export const putAccessIgnoreInviteResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})

export const putAccessRevokeGrantQueryParams = zod.object({
  "userId": zod.string()
})

export const putAccessRevokeGrantResponse = zod.object({
  "success": zod.boolean(),
  "message": zod.string()
})

