/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


export const getSessionResponse = zod.object({
  "session": zod.unknown().nullish(),
  "user": zod.unknown().nullish()
})

