/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from '../../client';




export const getLoginRedirect = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/login/redirect`, method: 'GET', signal
    },
      );
    }
  



export const getGetLoginRedirectQueryKey = () => {
    return [
    `/login/redirect`
    ] as const;
    }

    
export const getGetLoginRedirectQueryOptions = <TData = Awaited<ReturnType<typeof getLoginRedirect>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoginRedirect>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLoginRedirectQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLoginRedirect>>> = ({ signal }) => getLoginRedirect(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLoginRedirect>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLoginRedirectQueryResult = NonNullable<Awaited<ReturnType<typeof getLoginRedirect>>>
export type GetLoginRedirectQueryError = void


export function useGetLoginRedirect<TData = Awaited<ReturnType<typeof getLoginRedirect>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoginRedirect>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLoginRedirect>>,
          TError,
          Awaited<ReturnType<typeof getLoginRedirect>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLoginRedirect<TData = Awaited<ReturnType<typeof getLoginRedirect>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoginRedirect>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLoginRedirect>>,
          TError,
          Awaited<ReturnType<typeof getLoginRedirect>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLoginRedirect<TData = Awaited<ReturnType<typeof getLoginRedirect>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoginRedirect>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetLoginRedirect<TData = Awaited<ReturnType<typeof getLoginRedirect>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLoginRedirect>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLoginRedirectQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




